dist: xenial
language: python
python:
  - "3.6"
install:
  - pip install --upgrade pip
  - pip install -r dev-requirements.txt
  - pip install -r requirements.txt
script:
  - pytest -vvs --cov-report term-missing --cov=./ --black
  - mypy ./ --ignore-missing-imports
after_success:
  - coveralls
