dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install --upgrade pip
  - pip install black
  - pip install coverage
  - pip install mypy
  - pip install python-coveralls
  - pip install pytest
  - pip install pytest-black
  - pip install pytest-cov
  - pip install -r requirements.txt
script:
  - pytest -vvs --cov-report term-missing --cov=./ --black
  - mypy ./ --ignore-missing-imports
after_success:
  - coveralls
